spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/jwt-auth-service
      database: jwt-auth-service

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8090
