spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth-service
          uri: http://localhost:8090  # Make sure it's correct
          predicates:
            - Path=/auth/**
          filters:
            - JwtAuthenticationFilter

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


server:
  port: 8222
