spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth-service
          uri: http://localhost:8090
          predicates:
            - Path=/auth/**
        - id: product
          uri: http://localhost:9000
          predicates:
            - Path=/product/**
          filters:
            - JwtAuthenticationFilter  # Apply filter only to secured routes

  data:
    mongodb:
      uri: mongodb://localhost:27017/jwt-auth-service
      database: jwt-auth-service

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8222

logging:
  level:
    org.springframework.security: DEBUG